GROUPS = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"]

TEAMS = {
    "MEX": {"name": "Mexico",        "flag": "🇲🇽", "group": "A", "conf": "CONCACAF", "atk": 1.25, "def": 0.88},
    "KOR": {"name": "South Korea",   "flag": "🇰🇷", "group": "A", "conf": "AFC",      "atk": 1.10, "def": 0.95},
    "CZE": {"name": "Czech Rep.",    "flag": "🇨🇿", "group": "A", "conf": "UEFA",     "atk": 1.05, "def": 1.02},
    "ZAF": {"name": "South Africa",  "flag": "🇿🇦", "group": "A", "conf": "CAF",      "atk": 0.82, "def": 1.18},
    "CAN": {"name": "Canada",        "flag": "🇨🇦", "group": "B", "conf": "CONCACAF", "atk": 0.98, "def": 1.05},
    "BIH": {"name": "Bosnia & Hz.",  "flag": "🇧🇦", "group": "B", "conf": "UEFA",     "atk": 0.92, "def": 1.10},
    "SUI": {"name": "Switzerland",   "flag": "🇨🇭", "group": "B", "conf": "UEFA",     "atk": 1.08, "def": 0.92},
    "QAT": {"name": "Qatar",         "flag": "🇶🇦", "group": "B", "conf": "AFC",      "atk": 0.88, "def": 1.15},
    "GER": {"name": "Germany",       "flag": "🇩🇪", "group": "C", "conf": "UEFA",     "atk": 1.38, "def": 0.82},
    "CIV": {"name": "Ivory Coast",   "flag": "🇨🇮", "group": "C", "conf": "CAF",      "atk": 1.05, "def": 1.05},
    "ECU": {"name": "Ecuador",       "flag": "🇪🇨", "group": "C", "conf": "CONMEBOL", "atk": 0.95, "def": 1.02},
    "CUW": {"name": "Curacao",       "flag": "🇨🇼", "group": "C", "conf": "CONCACAF", "atk": 0.72, "def": 1.35},
    "NED": {"name": "Netherlands",   "flag": "🇳🇱", "group": "D", "conf": "UEFA",     "atk": 1.30, "def": 0.85},
    "JPN": {"name": "Japan",         "flag": "🇯🇵", "group": "D", "conf": "AFC",      "atk": 1.08, "def": 0.95},
    "SWE": {"name": "Sweden",        "flag": "🇸🇪", "group": "D", "conf": "UEFA",     "atk": 1.05, "def": 0.98},
    "TUN": {"name": "Tunisia",       "flag": "🇹🇳", "group": "D", "conf": "CAF",      "atk": 0.85, "def": 1.12},
    "BEL": {"name": "Belgium",       "flag": "🇧🇪", "group": "E", "conf": "UEFA",     "atk": 1.22, "def": 0.88},
    "EGY": {"name": "Egypt",         "flag": "🇪🇬", "group": "E", "conf": "CAF",      "atk": 0.92, "def": 1.05},
    "IRN": {"name": "Iran",          "flag": "🇮🇷", "group": "E", "conf": "AFC",      "atk": 0.88, "def": 1.08},
    "NZL": {"name": "New Zealand",   "flag": "🇳🇿", "group": "E", "conf": "OFC",      "atk": 0.72, "def": 1.30},
    "ESP": {"name": "Spain",         "flag": "🇪🇸", "group": "F", "conf": "UEFA",     "atk": 1.42, "def": 0.78},
    "URU": {"name": "Uruguay",       "flag": "🇺🇾", "group": "F", "conf": "CONMEBOL", "atk": 1.18, "def": 0.90},
    "KSA": {"name": "Saudi Arabia",  "flag": "🇸🇦", "group": "F", "conf": "AFC",      "atk": 0.92, "def": 1.10},
    "CPV": {"name": "Cape Verde",    "flag": "🇨🇻", "group": "F", "conf": "CAF",      "atk": 0.78, "def": 1.25},
    "FRA": {"name": "France",        "flag": "🇫🇷", "group": "G", "conf": "UEFA",     "atk": 1.45, "def": 0.78},
    "SEN": {"name": "Senegal",       "flag": "🇸🇳", "group": "G", "conf": "CAF",      "atk": 1.05, "def": 1.00},
    "NOR": {"name": "Norway",        "flag": "🇳🇴", "group": "G", "conf": "UEFA",     "atk": 1.15, "def": 0.95},
    "IRQ": {"name": "Iraq",          "flag": "🇮🇶", "group": "G", "conf": "AFC",      "atk": 0.82, "def": 1.22},
    "POR": {"name": "Portugal",      "flag": "🇵🇹", "group": "H", "conf": "UEFA",     "atk": 1.38, "def": 0.82},
    "ARG": {"name": "Argentina",     "flag": "🇦🇷", "group": "H", "conf": "CONMEBOL", "atk": 1.45, "def": 0.80},
    "CRO": {"name": "Croatia",       "flag": "🇭🇷", "group": "H", "conf": "UEFA",     "atk": 1.15, "def": 0.92},
    "ALG": {"name": "Algeria",       "flag": "🇩🇿", "group": "H", "conf": "CAF",      "atk": 0.95, "def": 1.10},
    "ENG": {"name": "England",       "flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "group": "I", "conf": "UEFA",     "atk": 1.30, "def": 0.85},
    "BRA": {"name": "Brazil",        "flag": "🇧🇷", "group": "I", "conf": "CONMEBOL", "atk": 1.42, "def": 0.80},
    "COL": {"name": "Colombia",      "flag": "🇨🇴", "group": "I", "conf": "CONMEBOL", "atk": 1.18, "def": 0.92},
    "MAR": {"name": "Morocco",       "flag": "🇲🇦", "group": "I", "conf": "CAF",      "atk": 1.05, "def": 0.95},
    "USA": {"name": "USA",           "flag": "🇺🇸", "group": "J", "conf": "CONCACAF", "atk": 1.12, "def": 0.95},
    "TUR": {"name": "Turkey",        "flag": "🇹🇷", "group": "J", "conf": "UEFA",     "atk": 1.15, "def": 0.98},
    "GHA": {"name": "Ghana",         "flag": "🇬🇭", "group": "J", "conf": "CAF",      "atk": 0.95, "def": 1.08},
    "COD": {"name": "Congo DR",      "flag": "🇨🇩", "group": "J", "conf": "CAF",      "atk": 0.82, "def": 1.18},
    "AUS": {"name": "Australia",     "flag": "🇦🇺", "group": "K", "conf": "AFC",      "atk": 0.98, "def": 1.05},
    "AUT": {"name": "Austria",       "flag": "🇦🇹", "group": "K", "conf": "UEFA",     "atk": 1.12, "def": 0.95},
    "SCO": {"name": "Scotland",      "flag": "🏴󠁧󠁢󠁳󠁣󠁴󠁿", "group": "K", "conf": "UEFA",     "atk": 0.92, "def": 1.08},
    "UZB": {"name": "Uzbekistan",    "flag": "🇺🇿", "group": "K", "conf": "AFC",      "atk": 0.82, "def": 1.20},
    "PAR": {"name": "Paraguay",      "flag": "🇵🇾", "group": "L", "conf": "CONMEBOL", "atk": 0.95, "def": 1.05},
    "JOR": {"name": "Jordan",        "flag": "🇯🇴", "group": "L", "conf": "AFC",      "atk": 0.85, "def": 1.15},
    "CHE": {"name": "Switzerland B", "flag": "🇨🇭", "group": "L", "conf": "UEFA",     "atk": 1.08, "def": 0.92},
    "VEN": {"name": "Venezuela",     "flag": "🇻🇪", "group": "L", "conf": "CONMEBOL", "atk": 0.90, "def": 1.10},
}

FIXTURES = [
    {"id":"A1","g":"A","h":"MEX","a":"ZAF","md":1,"status":"FINISHED","hs":2,"as":0,"date":"Jun 12"},
    {"id":"A2","g":"A","h":"KOR","a":"CZE","md":1,"status":"FINISHED","hs":2,"as":1,"date":"Jun 12"},
    {"id":"A3","g":"A","h":"CZE","a":"ZAF","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 18"},
    {"id":"A4","g":"A","h":"MEX","a":"KOR","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 18"},
    {"id":"A5","g":"A","h":"CZE","a":"MEX","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 24"},
    {"id":"A6","g":"A","h":"ZAF","a":"KOR","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 24"},
    {"id":"B1","g":"B","h":"CAN","a":"BIH","md":1,"status":"FINISHED","hs":1,"as":1,"date":"Jun 13"},
    {"id":"B2","g":"B","h":"SUI","a":"QAT","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 14"},
    {"id":"B3","g":"B","h":"SUI","a":"BIH","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 19"},
    {"id":"B4","g":"B","h":"CAN","a":"QAT","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 19"},
    {"id":"B5","g":"B","h":"BIH","a":"QAT","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 24"},
    {"id":"B6","g":"B","h":"CAN","a":"SUI","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 24"},
    {"id":"C1","g":"C","h":"GER","a":"CUW","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 14"},
    {"id":"C2","g":"C","h":"CIV","a":"ECU","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 14"},
    {"id":"C3","g":"C","h":"GER","a":"CIV","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 20"},
    {"id":"C4","g":"C","h":"ECU","a":"CUW","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 20"},
    {"id":"C5","g":"C","h":"ECU","a":"GER","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 25"},
    {"id":"C6","g":"C","h":"CUW","a":"CIV","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 25"},
    {"id":"D1","g":"D","h":"NED","a":"JPN","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 14"},
    {"id":"D2","g":"D","h":"SWE","a":"TUN","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 14"},
    {"id":"D3","g":"D","h":"NED","a":"SWE","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 20"},
    {"id":"D4","g":"D","h":"TUN","a":"JPN","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 20"},
    {"id":"D5","g":"D","h":"JPN","a":"SWE","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 25"},
    {"id":"D6","g":"D","h":"TUN","a":"NED","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 25"},
    {"id":"E1","g":"E","h":"BEL","a":"EGY","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 15"},
    {"id":"E2","g":"E","h":"IRN","a":"NZL","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 15"},
    {"id":"E3","g":"E","h":"BEL","a":"IRN","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 21"},
    {"id":"E4","g":"E","h":"NZL","a":"EGY","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 21"},
    {"id":"E5","g":"E","h":"EGY","a":"IRN","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 26"},
    {"id":"E6","g":"E","h":"NZL","a":"BEL","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 26"},
    {"id":"F1","g":"F","h":"ESP","a":"CPV","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 15"},
    {"id":"F2","g":"F","h":"KSA","a":"URU","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 15"},
    {"id":"F3","g":"F","h":"ESP","a":"KSA","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 21"},
    {"id":"F4","g":"F","h":"URU","a":"CPV","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 21"},
    {"id":"F5","g":"F","h":"CPV","a":"ESP","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 26"},
    {"id":"F6","g":"F","h":"URU","a":"KSA","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 26"},
    {"id":"G1","g":"G","h":"FRA","a":"SEN","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 16"},
    {"id":"G2","g":"G","h":"IRQ","a":"NOR","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 16"},
    {"id":"G3","g":"G","h":"FRA","a":"IRQ","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 22"},
    {"id":"G4","g":"G","h":"NOR","a":"SEN","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 22"},
    {"id":"G5","g":"G","h":"SEN","a":"IRQ","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 26"},
    {"id":"G6","g":"G","h":"NOR","a":"FRA","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 26"},
    {"id":"H1","g":"H","h":"POR","a":"ALG","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 16"},
    {"id":"H2","g":"H","h":"ARG","a":"CRO","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 16"},
    {"id":"H3","g":"H","h":"POR","a":"CRO","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 22"},
    {"id":"H4","g":"H","h":"ALG","a":"ARG","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 22"},
    {"id":"H5","g":"H","h":"CRO","a":"ALG","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 26"},
    {"id":"H6","g":"H","h":"ARG","a":"POR","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 26"},
    {"id":"I1","g":"I","h":"ENG","a":"BRA","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 17"},
    {"id":"I2","g":"I","h":"COL","a":"MAR","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 17"},
    {"id":"I3","g":"I","h":"ENG","a":"COL","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 23"},
    {"id":"I4","g":"I","h":"MAR","a":"BRA","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 23"},
    {"id":"I5","g":"I","h":"BRA","a":"COL","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 26"},
    {"id":"I6","g":"I","h":"MAR","a":"ENG","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 26"},
    {"id":"J1","g":"J","h":"USA","a":"TUR","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 17"},
    {"id":"J2","g":"J","h":"GHA","a":"COD","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 17"},
    {"id":"J3","g":"J","h":"USA","a":"GHA","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 23"},
    {"id":"J4","g":"J","h":"COD","a":"TUR","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 23"},
    {"id":"J5","g":"J","h":"TUR","a":"GHA","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 26"},
    {"id":"J6","g":"J","h":"COD","a":"USA","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 26"},
    {"id":"K1","g":"K","h":"AUS","a":"AUT","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 18"},
    {"id":"K2","g":"K","h":"SCO","a":"UZB","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 18"},
    {"id":"K3","g":"K","h":"AUS","a":"SCO","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 23"},
    {"id":"K4","g":"K","h":"UZB","a":"AUT","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 23"},
    {"id":"K5","g":"K","h":"AUT","a":"SCO","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 26"},
    {"id":"K6","g":"K","h":"UZB","a":"AUS","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 26"},
    {"id":"L1","g":"L","h":"PAR","a":"JOR","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 18"},
    {"id":"L2","g":"L","h":"CHE","a":"VEN","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 18"},
    {"id":"L3","g":"L","h":"PAR","a":"CHE","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 24"},
    {"id":"L4","g":"L","h":"VEN","a":"JOR","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 24"},
    {"id":"L5","g":"L","h":"JOR","a":"CHE","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 26"},
    {"id":"L6","g":"L","h":"VEN","a":"PAR","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 26"},
]
