# data.py — Poisson ratings + static fallback only.
#
# RATINGS: attack/defense parameters used by the Monte Carlo sim.
#          Keyed by internal team ID. live_data.py reads these.
#
# FALLBACK_TEAMS / FALLBACK_FIXTURES: used only when the live feed fails.
#   Team names and groups in the fallback mirror the last known state
#   but are NOT the source of truth — the live feed is.

GROUPS = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"]

# ---------------------------------------------------------------------------
# Poisson attack / defense ratings  (not available from the live feed)
# atk  = expected goals scored per match (relative to average)
# def  = expected goals conceded multiplier (lower = better defence)
# ---------------------------------------------------------------------------
RATINGS = {
    "MEX":    {"atk": 1.25, "def": 0.88},
    "ZAF":    {"atk": 0.82, "def": 1.18},
    "KOR":    {"atk": 1.10, "def": 0.95},
    "CZE":    {"atk": 1.05, "def": 1.02},
    "CAN":    {"atk": 0.98, "def": 1.05},
    "UEFA_A": {"atk": 0.95, "def": 1.05},
    "QAT":    {"atk": 0.88, "def": 1.15},
    "SUI":    {"atk": 1.08, "def": 0.92},
    "BRA":    {"atk": 1.42, "def": 0.80},
    "MAR":    {"atk": 1.05, "def": 0.95},
    "HTI":    {"atk": 0.72, "def": 1.30},
    "SCO":    {"atk": 0.92, "def": 1.08},
    "USA":    {"atk": 1.12, "def": 0.95},
    "PAR":    {"atk": 0.95, "def": 1.05},
    "AUS":    {"atk": 0.98, "def": 1.05},
    "UEFA_C": {"atk": 0.95, "def": 1.05},
    "GER":    {"atk": 1.38, "def": 0.82},
    "CUW":    {"atk": 0.72, "def": 1.35},
    "CIV":    {"atk": 1.05, "def": 1.05},
    "ECU":    {"atk": 0.95, "def": 1.02},
    "NED":    {"atk": 1.30, "def": 0.85},
    "JPN":    {"atk": 1.08, "def": 0.95},
    "UEFA_B": {"atk": 0.95, "def": 1.05},
    "TUN":    {"atk": 0.85, "def": 1.12},
    "BEL":    {"atk": 1.22, "def": 0.88},
    "EGY":    {"atk": 0.92, "def": 1.05},
    "IRN":    {"atk": 0.88, "def": 1.08},
    "NZL":    {"atk": 0.72, "def": 1.30},
    "ESP":    {"atk": 1.42, "def": 0.78},
    "CPV":    {"atk": 0.78, "def": 1.25},
    "KSA":    {"atk": 0.92, "def": 1.10},
    "URU":    {"atk": 1.18, "def": 0.90},
    "FRA":    {"atk": 1.45, "def": 0.78},
    "SEN":    {"atk": 1.05, "def": 1.00},
    "IC2":    {"atk": 0.85, "def": 1.15},
    "NOR":    {"atk": 1.15, "def": 0.95},
    "ARG":    {"atk": 1.45, "def": 0.80},
    "ALG":    {"atk": 0.95, "def": 1.10},
    "AUT":    {"atk": 1.12, "def": 0.95},
    "JOR":    {"atk": 0.85, "def": 1.15},
    "POR":    {"atk": 1.38, "def": 0.82},
    "IC1":    {"atk": 0.85, "def": 1.15},
    "UZB":    {"atk": 0.82, "def": 1.20},
    "COL":    {"atk": 1.18, "def": 0.92},
    "ENG":    {"atk": 1.30, "def": 0.85},
    "CRO":    {"atk": 1.15, "def": 0.92},
    "GHA":    {"atk": 0.95, "def": 1.08},
    "PAN":    {"atk": 0.80, "def": 1.20},
}

# ---------------------------------------------------------------------------
# Static fallback — used ONLY when the live feed is unreachable.
# Names here are last-known; they may lag the live feed for playoff slots.
# ---------------------------------------------------------------------------
FALLBACK_TEAMS = {
    "MEX":    {"name": "Mexico",         "group": "A", "conf": "CONCACAF", **RATINGS["MEX"]},
    "ZAF":    {"name": "South Africa",   "group": "A", "conf": "CAF",      **RATINGS["ZAF"]},
    "KOR":    {"name": "South Korea",    "group": "A", "conf": "AFC",      **RATINGS["KOR"]},
    "CZE":    {"name": "Czech Republic", "group": "A", "conf": "UEFA",     **RATINGS["CZE"]},
    "CAN":    {"name": "Canada",         "group": "B", "conf": "CONCACAF", **RATINGS["CAN"]},
    "UEFA_A": {"name": "UEFA Path A",    "group": "B", "conf": "UEFA",     **RATINGS["UEFA_A"]},
    "QAT":    {"name": "Qatar",          "group": "B", "conf": "AFC",      **RATINGS["QAT"]},
    "SUI":    {"name": "Switzerland",    "group": "B", "conf": "UEFA",     **RATINGS["SUI"]},
    "BRA":    {"name": "Brazil",         "group": "C", "conf": "CONMEBOL", **RATINGS["BRA"]},
    "MAR":    {"name": "Morocco",        "group": "C", "conf": "CAF",      **RATINGS["MAR"]},
    "HTI":    {"name": "Haiti",          "group": "C", "conf": "CONCACAF", **RATINGS["HTI"]},
    "SCO":    {"name": "Scotland",       "group": "C", "conf": "UEFA",     **RATINGS["SCO"]},
    "USA":    {"name": "USA",            "group": "D", "conf": "CONCACAF", **RATINGS["USA"]},
    "PAR":    {"name": "Paraguay",       "group": "D", "conf": "CONMEBOL", **RATINGS["PAR"]},
    "AUS":    {"name": "Australia",      "group": "D", "conf": "AFC",      **RATINGS["AUS"]},
    "UEFA_C": {"name": "UEFA Path C",    "group": "D", "conf": "UEFA",     **RATINGS["UEFA_C"]},
    "GER":    {"name": "Germany",        "group": "E", "conf": "UEFA",     **RATINGS["GER"]},
    "CUW":    {"name": "Curacao",        "group": "E", "conf": "CONCACAF", **RATINGS["CUW"]},
    "CIV":    {"name": "Ivory Coast",    "group": "E", "conf": "CAF",      **RATINGS["CIV"]},
    "ECU":    {"name": "Ecuador",        "group": "E", "conf": "CONMEBOL", **RATINGS["ECU"]},
    "NED":    {"name": "Netherlands",    "group": "F", "conf": "UEFA",     **RATINGS["NED"]},
    "JPN":    {"name": "Japan",          "group": "F", "conf": "AFC",      **RATINGS["JPN"]},
    "UEFA_B": {"name": "UEFA Path B",    "group": "F", "conf": "UEFA",     **RATINGS["UEFA_B"]},
    "TUN":    {"name": "Tunisia",        "group": "F", "conf": "CAF",      **RATINGS["TUN"]},
    "BEL":    {"name": "Belgium",        "group": "G", "conf": "UEFA",     **RATINGS["BEL"]},
    "EGY":    {"name": "Egypt",          "group": "G", "conf": "CAF",      **RATINGS["EGY"]},
    "IRN":    {"name": "Iran",           "group": "G", "conf": "AFC",      **RATINGS["IRN"]},
    "NZL":    {"name": "New Zealand",    "group": "G", "conf": "OFC",      **RATINGS["NZL"]},
    "ESP":    {"name": "Spain",          "group": "H", "conf": "UEFA",     **RATINGS["ESP"]},
    "CPV":    {"name": "Cape Verde",     "group": "H", "conf": "CAF",      **RATINGS["CPV"]},
    "KSA":    {"name": "Saudi Arabia",   "group": "H", "conf": "AFC",      **RATINGS["KSA"]},
    "URU":    {"name": "Uruguay",        "group": "H", "conf": "CONMEBOL", **RATINGS["URU"]},
    "FRA":    {"name": "France",         "group": "I", "conf": "UEFA",     **RATINGS["FRA"]},
    "SEN":    {"name": "Senegal",        "group": "I", "conf": "CAF",      **RATINGS["SEN"]},
    "IC2":    {"name": "IC Path 2",      "group": "I", "conf": "OTHER",    **RATINGS["IC2"]},
    "NOR":    {"name": "Norway",         "group": "I", "conf": "UEFA",     **RATINGS["NOR"]},
    "ARG":    {"name": "Argentina",      "group": "J", "conf": "CONMEBOL", **RATINGS["ARG"]},
    "ALG":    {"name": "Algeria",        "group": "J", "conf": "CAF",      **RATINGS["ALG"]},
    "AUT":    {"name": "Austria",        "group": "J", "conf": "UEFA",     **RATINGS["AUT"]},
    "JOR":    {"name": "Jordan",         "group": "J", "conf": "AFC",      **RATINGS["JOR"]},
    "POR":    {"name": "Portugal",       "group": "K", "conf": "UEFA",     **RATINGS["POR"]},
    "IC1":    {"name": "IC Path 1",      "group": "K", "conf": "OTHER",    **RATINGS["IC1"]},
    "UZB":    {"name": "Uzbekistan",     "group": "K", "conf": "AFC",      **RATINGS["UZB"]},
    "COL":    {"name": "Colombia",       "group": "K", "conf": "CONMEBOL", **RATINGS["COL"]},
    "ENG":    {"name": "England",        "group": "L", "conf": "UEFA",     **RATINGS["ENG"]},
    "CRO":    {"name": "Croatia",        "group": "L", "conf": "UEFA",     **RATINGS["CRO"]},
    "GHA":    {"name": "Ghana",          "group": "L", "conf": "CAF",      **RATINGS["GHA"]},
    "PAN":    {"name": "Panama",         "group": "L", "conf": "CONCACAF", **RATINGS["PAN"]},
}

FALLBACK_FIXTURES = [
    # Group A
    {"id":"A1","g":"A","h":"MEX","a":"ZAF","md":1,"status":"FINISHED","hs":2,"as":0,"date":"Jun 11"},
    {"id":"A2","g":"A","h":"KOR","a":"CZE","md":1,"status":"FINISHED","hs":2,"as":1,"date":"Jun 11"},
    {"id":"A3","g":"A","h":"CZE","a":"ZAF","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 18"},
    {"id":"A4","g":"A","h":"MEX","a":"KOR","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 18"},
    {"id":"A5","g":"A","h":"CZE","a":"MEX","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 24"},
    {"id":"A6","g":"A","h":"ZAF","a":"KOR","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 24"},
    # Group B
    {"id":"B1","g":"B","h":"CAN","a":"UEFA_A","md":1,"status":"FINISHED","hs":1,"as":1,"date":"Jun 12"},
    {"id":"B2","g":"B","h":"QAT","a":"SUI","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 13"},
    {"id":"B3","g":"B","h":"SUI","a":"UEFA_A","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 18"},
    {"id":"B4","g":"B","h":"CAN","a":"QAT","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 18"},
    {"id":"B5","g":"B","h":"SUI","a":"CAN","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 24"},
    {"id":"B6","g":"B","h":"UEFA_A","a":"QAT","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 24"},
    # Group C
    {"id":"C1","g":"C","h":"BRA","a":"MAR","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 13"},
    {"id":"C2","g":"C","h":"HTI","a":"SCO","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 13"},
    {"id":"C3","g":"C","h":"SCO","a":"MAR","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 19"},
    {"id":"C4","g":"C","h":"BRA","a":"HTI","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 19"},
    {"id":"C5","g":"C","h":"SCO","a":"BRA","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 24"},
    {"id":"C6","g":"C","h":"MAR","a":"HTI","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 24"},
    # Group D
    {"id":"D1","g":"D","h":"USA","a":"PAR","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 12"},
    {"id":"D2","g":"D","h":"AUS","a":"UEFA_C","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 13"},
    {"id":"D3","g":"D","h":"USA","a":"AUS","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 19"},
    {"id":"D4","g":"D","h":"UEFA_C","a":"PAR","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 19"},
    {"id":"D5","g":"D","h":"UEFA_C","a":"USA","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 25"},
    {"id":"D6","g":"D","h":"PAR","a":"AUS","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 25"},
    # Group E
    {"id":"E1","g":"E","h":"GER","a":"CUW","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 14"},
    {"id":"E2","g":"E","h":"CIV","a":"ECU","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 14"},
    {"id":"E3","g":"E","h":"GER","a":"CIV","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 20"},
    {"id":"E4","g":"E","h":"ECU","a":"CUW","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 20"},
    {"id":"E5","g":"E","h":"CUW","a":"CIV","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 25"},
    {"id":"E6","g":"E","h":"ECU","a":"GER","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 25"},
    # Group F
    {"id":"F1","g":"F","h":"NED","a":"JPN","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 14"},
    {"id":"F2","g":"F","h":"UEFA_B","a":"TUN","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 14"},
    {"id":"F3","g":"F","h":"NED","a":"UEFA_B","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 20"},
    {"id":"F4","g":"F","h":"TUN","a":"JPN","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 20"},
    {"id":"F5","g":"F","h":"JPN","a":"UEFA_B","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 25"},
    {"id":"F6","g":"F","h":"TUN","a":"NED","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 25"},
    # Group G
    {"id":"G1","g":"G","h":"BEL","a":"EGY","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 15"},
    {"id":"G2","g":"G","h":"IRN","a":"NZL","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 15"},
    {"id":"G3","g":"G","h":"BEL","a":"IRN","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 21"},
    {"id":"G4","g":"G","h":"NZL","a":"EGY","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 21"},
    {"id":"G5","g":"G","h":"EGY","a":"IRN","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 26"},
    {"id":"G6","g":"G","h":"NZL","a":"BEL","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 26"},
    # Group H
    {"id":"H1","g":"H","h":"ESP","a":"CPV","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 15"},
    {"id":"H2","g":"H","h":"KSA","a":"URU","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 15"},
    {"id":"H3","g":"H","h":"ESP","a":"KSA","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 21"},
    {"id":"H4","g":"H","h":"URU","a":"CPV","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 21"},
    {"id":"H5","g":"H","h":"CPV","a":"KSA","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 26"},
    {"id":"H6","g":"H","h":"URU","a":"ESP","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 26"},
    # Group I
    {"id":"I1","g":"I","h":"FRA","a":"SEN","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 16"},
    {"id":"I2","g":"I","h":"IC2","a":"NOR","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 16"},
    {"id":"I3","g":"I","h":"FRA","a":"IC2","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 22"},
    {"id":"I4","g":"I","h":"NOR","a":"SEN","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 22"},
    {"id":"I5","g":"I","h":"NOR","a":"FRA","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 26"},
    {"id":"I6","g":"I","h":"SEN","a":"IC2","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 26"},
    # Group J
    {"id":"J1","g":"J","h":"ARG","a":"ALG","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 16"},
    {"id":"J2","g":"J","h":"AUT","a":"JOR","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 16"},
    {"id":"J3","g":"J","h":"ARG","a":"AUT","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 22"},
    {"id":"J4","g":"J","h":"JOR","a":"ALG","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 22"},
    {"id":"J5","g":"J","h":"ALG","a":"AUT","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 27"},
    {"id":"J6","g":"J","h":"JOR","a":"ARG","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 27"},
    # Group K
    {"id":"K1","g":"K","h":"POR","a":"IC1","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 17"},
    {"id":"K2","g":"K","h":"UZB","a":"COL","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 17"},
    {"id":"K3","g":"K","h":"POR","a":"UZB","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 23"},
    {"id":"K4","g":"K","h":"COL","a":"IC1","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 23"},
    {"id":"K5","g":"K","h":"COL","a":"POR","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 27"},
    {"id":"K6","g":"K","h":"IC1","a":"UZB","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 27"},
    # Group L
    {"id":"L1","g":"L","h":"ENG","a":"CRO","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 17"},
    {"id":"L2","g":"L","h":"GHA","a":"PAN","md":1,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 17"},
    {"id":"L3","g":"L","h":"ENG","a":"GHA","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 23"},
    {"id":"L4","g":"L","h":"PAN","a":"CRO","md":2,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 23"},
    {"id":"L5","g":"L","h":"PAN","a":"ENG","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 27"},
    {"id":"L6","g":"L","h":"CRO","a":"GHA","md":3,"status":"SCHEDULED","hs":None,"as":None,"date":"Jun 27"},
]
